# You Podfile should look similar to this file. Whether you use_frameworks! or not, the following configuration should work.
#
# However if you DO NOT use_frameworks! and you prefer to install pods instead of
# dragging the AirMaps directory into your project, refer to the comments below (steps 1~4)
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#plugin 'cocoapods-fix-react-native'

source 'https://github.com/CocoaPods/Specs.git'
target 'sanship' do
  # Pods for sanship
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  # pod 'GoogleMaps'
  # pod 'Google-Maps-iOS-Utils'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  # pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  pod 'FBSDKCoreKit', '~> 5.8', :modular_headers => true

  target 'sanshipTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!

  # pod 'RNAppTour', :path => '../node_modules/react-native-app-tour/ios'

  # use_frameworks!

  # pod 'MaterialShowcase'
end

# when not using frameworks this might be necessary, but try without it first and see if `pod install` works (3/4):
# THIS IS ONLY NECESSARY IF YOU NEED GoogleMaps SUPPORT
# pre_install do |installer|
  # # copied from https://github.com/CocoaPods/CocoaPods/issues/2926
  # # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  # def installer.verify_no_static_framework_transitive_dependencies; end
# end
target 'sanship-tvOS' do
  # Pods for sanship-tvOS

  target 'sanship-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# when not using frameworks (4/4):
# THIS IS ONLY NECESSARY IF YOU NEED GoogleMaps SUPPORT
# #Crud, this shouldn't be necessary, but https://github.com/CocoaPods/CocoaPods/issues/5429
# post_install do |installer|
#   	installer.pods_project.targets.each do |target|
# 		target.build_configurations.each do |config|
#       		config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
#     	end
#   	end
# end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "react-native-google-maps"
#       target.build_configurations.each do |config|
#         config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#       end
#     end
#   end
# end

pre_install do |installer|
  # workaround for CocoaPods/CocoaPods#3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
